### ISSUE TITLE
How to save a texture object

### ISSUE THREAD

**Issue by SJAEO** [xuxy09/Texformer#8]
Hello,

I can get the 2d rendered image like output result of example.
How can I get the 3D rendered object with texture of input image?

Thanks!

**Comment by xuxy09** [comment]
I am not quite sure about your question. Could you better explain this?

**Comment by SJAEO** [comment]
@xuxy09 

thanks for reply

I executed the demo program and I only get the following image result

![texformer_demo](https://user-images.githubusercontent.com/27358581/179660273-23b0f62c-99a4-41bf-a764-baa04078860a.png)

How to get 3D human model?
Need to use RSC-Net?

Thanks!

**Comment by Yuanhong200727** [comment]
@xuxy09 
Sorry,I still don't understand how to save the 3D human body mesh from the line 44 in demo.py.Could you give me the relevant code to achieve this?
Thank you!
